sudo: required
language: ruby
rvm: 2.2
node_js: "0.10"
before_script:
  - npm install .github/crafter/
  - gem install countries
  - gem install awesome_bot
  - sudo pip install json-spec
script:
  - awesome_bot submission.json -w skillsmatter,cfict,swiftbynorthwest,it.droidcon,gotoams.nl,addconf,codeeurope.pl,droidconvn.com,developerweek.com,facebook.com,eventbrite.com,mobiusconf.com,2018.mobiconf.org
  - json validate --schema-file=.github/schema.json --document-file=submission.json
after_success:
  - node .github/crafter/job
  - ruby .github/convert.rb
  - ./.github/deploy.sh
