sudo: required
language: ruby
rvm: 2.2
node_js: "0.10"
before_script:
  - npm install .github/crafter/
  - gem install countries
  - gem install awesome_bot
  - sudo pip install json-spec
script:
  - awesome_bot contents.json -w skillsmatter,cfict,swiftbynorthwest,it.droidcon,gotoams.nl,addconf,codeeurope.pl,droidconvn.com
  - json validate --schema-file=.github/schema.json --document-file=contents.json
after_success:
  - ruby .github/convert.rb
  - node .github/crafter/job
  - ./.github/deploy.sh
