sudo: required
language: ruby
rvm: 2.2
node_js: "0.10"
before_script:
  - npm install .github/crafter/
  - gem install countries
  - sudo pip install json-spec
script:
  - json validate --schema-file=.github/schema.json --document-file=submission.json
after_success:
  - node .github/crafter/job
  - ./.github/deploy.sh
